Add changes after review
klenin/EGEpy pull request #58
Opened 2022-04-27 05:46 UTC by Drokonor

2022-04-27 11:23 UTC, tonichoff requested changes
Требуются минорные исправления

2022-04-27 11:23 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +        self.text = f'''<p>В велокроссе участвуют {text_for_athletes}.
Тут ошибка в тексте задачи

2022-04-27 11:23 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +        self.text = f'''<p>В велокроссе участвуют {text_for_athletes}.
Тут ошибка в тексте задачи

2022-04-27 11:23 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +    def __init__(self, rnd):
Надо вызвать конструктор базового класса и передать ему `rnd`

2022-04-27 11:23 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +    def get_amount_of_bits(self, letters_and_digits):
Метод называется `get_amount_of_bits`, а возвращает `amount_of_bits_for_one_symbol`. Из-за наименований у меня возникает непонимание, что всё таки возвращает этот метод. Надо либо переменную переименовать, либо метод

2022-04-27 11:23 UTC, tonichoff commented on gen.py
> -from EGE.Gen.EGE import A01, A02, A03, A04, A05, A06, A07, A08, A09, A10, A11, A12, A13, A15, A16, A17, A18
Надо убрать все изменения в этом файле

2022-04-27 14:53 UTC, Drokonor commented on EGE/Gen/EGE2022/N11.py
> +        self.text = f'''<p>В велокроссе участвуют {text_for_athletes}.
Не вижу ошибки, в каком слове?

2022-04-27 14:54 UTC, Drokonor commented on EGE/Gen/EGE2022/N11.py
> +        self.text = f'''<p>В велокроссе участвуют {text_for_athletes}.
Не вижу ошибки, в каком слове?

2022-04-27 14:54 UTC, Drokonor commented on EGE/Gen/EGE2022/N11.py
> +    def get_amount_of_bits(self, letters_and_digits):
Исправил, поменяв amount_of_bits_for_one_symbol на amount_of_bits.

2022-04-27 15:01 UTC, Drokonor commented on EGE/Gen/EGE2022/N11.py
> +    def __init__(self, rnd):
Разве это уже не сделано в этих 2х строках:
    def __init__(self, rnd):
        self.rnd = rnd

2022-04-27 15:04 UTC, Drokonor commented on gen.py
> -from EGE.Gen.EGE import A01, A02, A03, A04, A05, A06, A07, A08, A09, A10, A11, A12, A13, A15, A16, A17, A18
Изменения убрал

2022-04-28 08:31 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +        self.text = f'''<p>В велокроссе участвуют {text_for_athletes}.
Дальше по тексту. Не конкретно в этой строке

2022-04-28 08:31 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +        self.text = f'''<p>В велокроссе участвуют {text_for_athletes}.
Дальше по тексту. Не конкретно в этой строке

2022-04-28 08:32 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +    def __init__(self, rnd):
Нет. Нужно так `super().__init__(rnd)`

2022-04-28 08:38 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +    def __init__(self, rnd):
`def __init__(self, rnd: EGE.Random.Random):
        super().__init__(rnd, text, correct)
        ...
`

2022-04-28 09:45 UTC, Drokonor commented on EGE/Gen/EGE2022/N11.py
> +    def __init__(self, rnd):
Добавил изменения

2022-04-28 10:57 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +        self.text = f'''<p>В велокроссе участвуют {text_for_athletes}.
Ошибки никакой нет, я не дочитал текст

2022-04-28 10:57 UTC, tonichoff commented on EGE/Gen/EGE2022/N11.py
> +        self.text = f'''<p>В велокроссе участвуют {text_for_athletes}.
Ошибки никакой нет, я не дочитал текст

2022-04-28 11:00 UTC, tonichoff approved these changes

2022-05-01 05:35 UTC, tonichoff approved these changes

2022-05-01 05:35 UTC, merged